name: Deploy to IC

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'testnet'
        type: choice
        options:
          - testnet
          - mainnet

jobs:
  verify-build:
    name: 'Verify Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      # Verify that the dist directory exists
      - name: Verify dist directory
        run: |
          echo "Using pre-built files from the repository"
          ls -la dist
      
      - name: Success message
        run: |
          echo "Build verification successful!"
          echo "Note: Actual deployment to the Internet Computer is done manually from the developer's machine."
