name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install dfx
      uses: dfinity/setup-dfx@main
    
    - name: Start local replica
      run: |
        dfx start --background
        mkdir -p .dfx/local
        echo '{}' > .dfx/local/canister_ids.json
        dfx canister create --all
        dfx generate
    
    - name: Build
      run: |
        export NODE_OPTIONS="--no-experimental-fetch --experimental-global-webcrypto"
        npm run build
